### ISSUE TITLE
Open in Browser

### ISSUE THREAD

**Issue by jeremylenz** [learn-co-curriculum/css-kitten-wheelbarrow#7]
The "Open in Browser" option doesn't seem to be available in Learn IDE.  Was this written for a previous version?  I've just been dragging the tab from Learn IDE to a browser tab and that seems to work ok.

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/css-kitten-wheelbarrow/commit/105e9a277015e4b688b40fa519701c5971a74ccf.

Thanks @jeremylenz !
